# Generated by Django 3.1.4 on 2021-01-16 09:56

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='balance',
            field=models.IntegerField(default=api.models.random_val, verbose_name='Остаток на складе'),
        ),
    ]
